### PR TITLE
add dotnet cards

### PR DESCRIPTION
**Pull request by bradygaster**
adding the dotnet card images Hanselman used in the //build/ 2020 keynote.

### CODE REVIEW

**Comment by akoeplinger** [comment]
there's a stray `.DS_Store` that can be removed

**Comment by mgroves** [comment]
Yes and maybe .DS_Store can just be added to a gitignore?

**Comment by bradygaster** [comment]
#facepalm. that file hates me.

**Comment by bradygaster** [comment]
done. sorry. this on .DS_Store files. 

tenor-95510216

**Pull request merged**
